=== pombreda/smartform/py/xsd/descriptor-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.rpath.com/permanent/descriptor-1.0.xsd"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:dsc="http://www.rpath.com/permanent/descriptor-1.0.xsd"
        xmlns="http://www.rpath.com/permanent/descriptor-1.0.xsd">

    <xsd:element name="descriptor" type="dsc:descriptorType" />

    <xsd:complexType name="descriptorType">
      <xsd:sequence>
        <xsd:element name="metadata" type="dsc:metadataType" />
        <xsd:element name="dataFields" type="dsc:dataFieldsType" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:anyURI" />
      <xsd:attribute name="version" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="metadataType">
      <xsd:sequence>
        <xsd:element name="displayName" type="xsd:string" />
        <xsd:element name="rootElement" type="xsd:string"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="descriptions" type="dsc:descriptionsType" />
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="descriptionsType">
      <xsd:sequence>
        <xsd:element name="desc" type="dsc:descType"
            minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="descType">
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="lang" type="xsd:string" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="dataFieldsType">
      <xsd:sequence>
        <xsd:element name="field" type="dsc:dataFieldType"
            minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="helpType">
      <xsd:attribute name="lang" type="xsd:string" />
      <xsd:attribute name="href" type="xsd:anyURI" use="required" />
    </xsd:complexType>

    <xsd:complexType name="dataFieldType">
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string" />
        <xsd:element name="descriptions" type="dsc:descriptionsType" 
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="help" type="dsc:helpType"
            minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="type" type="xsd:string"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="enumeratedType" type="dsc:enumeratedTypeType"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="multiple" type="xsd:boolean"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="default" type="xsd:string"
            minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="constraints" type="dsc:constraintsType"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="required" type="xsd:boolean"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="allowFileContent" type="xsd:boolean"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="hidden" type="xsd:boolean"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="password" type="xsd:boolean"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="readonly" type="xsd:boolean"
            minOccurs="0" maxOccurs="1" />
        <xsd:element name="conditional" type="dsc:conditionalType"
            minOccurs="0" maxOccurs="1" />
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="enumeratedTypeType">
      <xsd:sequence>
        <xsd:element name="describedValue" type="dsc:describedValueType"
            minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="describedValueType">
      <xsd:sequence>
        <xsd:element name="descriptions" type="dsc:descriptionsType" />
        <xsd:element name="key" type="xsd:string" />
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="constraintsType">
      <xsd:sequence>
        <xsd:element name="descriptions" type="dsc:descriptionsType"
            minOccurs="0" maxOccurs="1" />
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element name="range" type="dsc:rangeType" />
          <xsd:element name="legalValues" type="dsc:legalValuesType" />
          <xsd:element name="regexp" type="dsc:regexpType" />
          <xsd:element name="length" type="dsc:lengthType" />
        </xsd:choice>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="rangeType">
      <xsd:sequence>
        <xsd:element name="min" type="xsd:positiveInteger"/>
        <xsd:element name="max" type="xsd:positiveInteger"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="legalValuesType">
      <xsd:sequence>
        <xsd:element name="item" type="xsd:string"
            minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="regexpType">
      <xsd:simpleContent>
        <xsd:extension base="xsd:string" />
      </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="lengthType">
      <xsd:simpleContent>
        <xsd:extension base="xsd:unsignedInt" />
      </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="conditionalType">
      <xsd:sequence>
        <xsd:element name="fieldName" type="xsd:string"/>
        <xsd:element name="operator">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="eq"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="value" type="xsd:string"/>
      </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== pombreda/smartform/as3/smartform-test/src/data/test/launch_vsphere.xml
<descriptor xmlns="http://www.rpath.com/permanent/descriptor-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rpath.com/permanent/descriptor-1.0.xsd descriptor-1.0.xsd">
<metadata>
<displayName>
VMware Launch Parameters
</displayName>
<descriptions>
<desc>
VMware Launch Parameters
</desc>
</descriptions>
</metadata>
<dataFields>
<field>
<name>
imageId
</name>
<descriptions>
<desc>
Image ID
</desc>
</descriptions>
<type>
str
</type>
<constraints>
<range>
<min>
1
</min>
<max>
32
</max>
</range>
</constraints>
<required>
true
</required>
<hidden>
true
</hidden>
</field>
<field>
<name>
instanceName
</name>
<descriptions>
<desc>
Instance Name
</desc>
</descriptions>
<help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/launch/instanceName.html" />
<type>
str
</type>
<constraints>
<length>
32
</length>
</constraints>
<required>
true
</required>
</field>
<field>
<name>
instanceDescription
</name>
<descriptions>
<desc>
Instance Description
</desc>
</descriptions>
<help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/launch/instanceDescription.html" />
<type>
str
</type>
<constraints>
<length>
128
</length>
</constraints>
</field>
<field>
<name>
dataCenter
</name>
<descriptions>
<desc>
Data Center
</desc>
</descriptions>
<help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/launch/dataCenter.html" />
<enumeratedType>
<describedValue>
<descriptions>
<desc>
rPath4
</desc>
</descriptions>
<key>
datacenter-6098
</key>
</describedValue>
</enumeratedType>
<default>
datacenter-6098
</default>
<required>
true
</required>
</field>
<field>
<name>
cr-datacenter-6098
</name>
<descriptions>
<desc>
Compute Resource
</desc>
</descriptions>
<help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/launch/computeResource.html" />
<enumeratedType>
<describedValue>
<descriptions>
<desc>
eng lab
</desc>
</descriptions>
<key>
domain-c6103
</key>
</describedValue>
</enumeratedType>
<default>
domain-c6103
</default>
<required>
true
</required>
<conditional>
<fieldName>
dataCenter
</fieldName>
<operator>
eq
</operator>
<value>
datacenter-6098
</value>
</conditional>
</field>
<field>
<name>
dataStore-domain-c6103
</name>
<descriptions>
<desc>
Data Store
</desc>
</descriptions>
<help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/launch/dataStore.html" />
<enumeratedType>
<describedValue>
<descriptions>
<desc>
nfs-isos - 472 GiB free
</desc>
</descriptions>
<key>
datastore-6367
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
high-volume01 - 307 GiB free
</desc>
</descriptions>
<key>
datastore-6375
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
high-volume-temp - 158 GiB free
</desc>
</descriptions>
<key>
datastore-6377
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
common-temp - 365 GiB free
</desc>
</descriptions>
<key>
datastore-6379
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
esx04-local - 230 GiB free
</desc>
</descriptions>
<key>
datastore-9898
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
nas1 target1 - 284 GiB free
</desc>
</descriptions>
<key>
datastore-11884
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
nas1 target2 - 596 GiB free
</desc>
</descriptions>
<key>
datastore-11886
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
nas1 target3 - 626 GiB free
</desc>
</descriptions>
<key>
datastore-11888
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
nas1 target4 - 621 GiB free
</desc>
</descriptions>
<key>
datastore-11890
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
esx05-local - 141 GiB free
</desc>
</descriptions>
<key>
datastore-8228
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
esx03-local - 102 GiB free
</desc>
</descriptions>
<key>
datastore-8234
</key>
</describedValue>
<describedValue>
<descriptions>
<desc>
esx02-local - 291 GiB free
</desc>
</descriptions>
<key>
datastore-9877
</key>
</describedValue>
</enumeratedType>
<default>
datastore-6367
</default>
<required>
true
</required>
<conditional>
<fieldName>
cr-datacenter-6098
</fieldName>
<operator>
eq
</operator>
<value>
domain-c6103
</value>
</conditional>
</field>
<field>
<name>
resourcePool-domain-c6103
</name>
<descriptions>
<desc>
Resource Pool
</desc>
</descriptions>
<help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/launch/resourcePool.html" />
<enumeratedType>
<describedValue>
<descriptions>
<desc>
Resources
</desc>
</descriptions>
<key>
resgroup-6105
</key>
</describedValue>
</enumeratedType>
<default>
resgroup-6105
</default>
<required>
true
</required>
<conditional>
<fieldName>
cr-datacenter-6098
</fieldName>
<operator>
eq
</operator>
<value>
domain-c6103
</value>
</conditional>
</field>
</dataFields>
</descriptor>

=== pombreda/smartform/as3/smartform-test/src/data/test/configure_ec2.xml
<?xml version="1.0" encoding="utf-8"?>
<descriptor xmlns="http://www.rpath.com/permanent/descriptor-1.0.xsd" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.rpath.com/permanent/descriptor-1.0.xsd descriptor-1.0.xsd">
 <metadata>
   <displayName>EC2 Cloud Configuration</displayName>
   <descriptions>
     <desc>Configure Amazon EC2</desc>
   </descriptions>
 </metadata>
 <dataFields>
   <field>
     <name>name</name>
     <descriptions>
       <desc>Name</desc>
     </descriptions>
     <type>str</type>
     <default>aws</default>
     <hidden>true</hidden>
   </field>
   <field>
     <name>cloudAlias</name>
     <descriptions>
       <desc>Cloud Alias</desc>
     </descriptions>
     <type>str</type>
     <default>ec2</default>
     <hidden>true</hidden>
   </field>
   <field>
     <name>fullDescription</name>
     <descriptions>
       <desc>Full Description</desc>
     </descriptions>
     <type>str</type>
     <default>Amazon Elastic Compute Cloud</default>
     <hidden>true</hidden>
   </field>
   <field>
     <name>accountId</name>
     <descriptions>
       <desc>AWS Account Number</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/ec2/help/configuration/accountNumber.html"/>
     <type>str</type>
     <constraints>
       <descriptions>
         <desc>This field cannot be more than 12 characters in length</desc>
       </descriptions>
       <length>12</length>
     </constraints>
     <required>true</required>
   </field>
   <field>
     <name>publicAccessKeyId</name>
     <descriptions>
       <desc>Access Key ID</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/ec2/help/configuration/accessKey.html"/>
     <type>str</type>
     <constraints>
       <descriptions>
         <desc>This field cannot be more than 100 characters in length</desc>
       </descriptions>
       <length>100</length>
     </constraints>
     <required>true</required>
   </field>
   <field>
     <name>secretAccessKey</name>
     <descriptions>
       <desc>Secret Access Key</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/ec2/help/configuration/secretAccessKey.html"/>
     <type>str</type>
     <constraints>
       <descriptions>
         <desc>256 is all the characters this field can hold</desc>
       </descriptions>
       <length>256</length>
     </constraints>
     <required>true</required>
     <password>true</password>
   </field>
   <field>
     <name>certificateData</name>
     <descriptions>
       <desc>X.509 Certificate</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/ec2/help/configuration/certificateData.html"/>
     <type>str</type>
     <constraints>
       <descriptions>
         <desc>The certificate must start with '-----BEGIN CERTIFICATE-----', end with '-----END CERTIFICATE-----', and have a maximum length of 16384 characters.</desc>
       </descriptions>
       <regexp>^\s*-----BEGIN CERTIFICATE-----.*-----END CERTIFICATE-----\s*$</regexp>
       <length>16384</length>
     </constraints>
     <required>true</required>
     <allowFileContent>true
</allowFileContent>
   </field>
   <field>
     <name>certificateKeyData</name>
     <descriptions>
       <desc>X.509 Private Key</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/ec2/help/configuration/certificateKeyData.html"/>
     <type>str</type>
     <constraints>
       <descriptions>
         <desc>The key must start with '-----BEGIN PRIVATE KEY-----', end with '----END PRIVATE KEY-----', and have a maximum length of 16384 characters.</desc>
       </descriptions>
       <regexp>^\s*-----BEGIN (\S+ )?PRIVATE KEY-----.*-----END (\S+ )?PRIVATE KEY-----\s*$</regexp>
       <length>16384</length>
     </constraints>
     <required>true</required>
     <allowFileContent>true
</allowFileContent>
   </field>
   <field>
     <name>s3Bucket</name>
     <descriptions>
       <desc>S3 Bucket</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/ec2/help/configuration/s3Bucket.html"/>
     <type>str</type>
     <constraints>
       <descriptions>
         <desc>The S3 bucket name cannot be more than 32 characters long</desc>
       </descriptions>
       <length>32</length>
     </constraints>
     <required>true</required>
   </field>
 </dataFields>
</descriptor>

=== pombreda/smartform/as3/smartform-test/src/data/test/descriptors/configure_vsphere.xml
<?xml version="1.0" encoding="utf-8"?>
<descriptor xmlns="http://www.rpath.com/permanent/descriptor-1.0.xsd" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.rpath.com/permanent/descriptor-1.0.xsd descriptor-1.0.xsd">
 <metadata>
   <displayName>VMware Configuration</displayName>
   <descriptions>
     <desc>Configure VMware</desc>
   </descriptions>
 </metadata>
 <dataFields>
   <field>
     <name>name</name>
     <descriptions>
       <desc>Server Name</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/configuration/serverName.html"/>
     <type>str</type>
     <required>true</required>
   </field>
   <field>
     <name>alias</name>
     <descriptions>
       <desc>Cloud Alias</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/configuration/alias.html"/>
     <type>str</type>
     <required>true</required>
   </field>
   <field>
     <name>description</name>
     <descriptions>
       <desc>Full Description</desc>
     </descriptions>
     <help href="https://rbanext-eng.eng.rpath.com/catalog/clouds/vmware/help/configuration/description.html"/>
     <type>str</type>
     <required>true</required>
   </field>
 </dataFields>
</descriptor>

=== pombreda/smartform/as3/smartform-test/src/data/test/launch_ec2.xml
<?xml version="1.0" encoding="utf-8"?>
<descriptor xmlns="http://www.rpath.com/permanent/descriptor-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rpath.com/permanent/descriptor-1.0.xsd descriptor-1.0.xsd">
    <metadata>
    <displayName>
    Amazon EC2 Launch Parameters
    </displayName>
    <descriptions>
    <desc>
    Amazon EC2 Launch Parameters
    </desc>
    </descriptions>
    </metadata>
    <dataFields>
    <field>
    <name>
    imageId
    </name>
    <descriptions>
    <desc>
    Image ID
    </desc>
    </descriptions>
    <type>
    str
    </type>
    <constraints>
    <range>
    <min>
    1
    </min>
    <max>
    32
    </max>
    </range>
    </constraints>
    <required>
    true
    </required>
    <hidden>
    true
    </hidden>
    </field>
    <field>
    <name>
    instanceType
    </name>
    <descriptions>
    <desc>
    Instance Type
    </desc>
    <desc lang="fr_FR">
    Type de l'instance
    </desc>
    </descriptions>
    <help href="https://test154.rdu.rpath.com/catalog/clouds/ec2/help/launch/instanceTypes.html" />
    <enumeratedType>
    <describedValue>
    <descriptions>
    <desc>
    Small
    </desc>
    </descriptions>
    <key>
    m1.small
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    Large
    </desc>
    </descriptions>
    <key>
    m1.large
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    Extra Large
    </desc>
    </descriptions>
    <key>
    m1.xlarge
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    High-CPU Medium
    </desc>
    </descriptions>
    <key>
    c1.medium
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    High-CPU Extra Large
    </desc>
    </descriptions>
    <key>
    c1.xlarge
    </key>
    </describedValue>
    </enumeratedType>
    <default>
    m1.small
    </default>
    <required>
    true
    </required>
    </field>
    <field>
    <name>
    availabilityZone
    </name>
    <descriptions>
    <desc>
    Availability Zone
    </desc>
    <desc lang="fr_FR">
    Zone de disponibilit‚àö¬©
    </desc>
    </descriptions>
    <help href="https://test154.rdu.rpath.com/catalog/clouds/ec2/help/launch/availabilityZones.html" />
    <enumeratedType>
    <describedValue>
    <descriptions>
    <desc>
    us-east-1a
    </desc>
    </descriptions>
    <key>
    us-east-1a
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    us-east-1b
    </desc>
    </descriptions>
    <key>
    us-east-1b
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    us-east-1c
    </desc>
    </descriptions>
    <key>
    us-east-1c
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    us-east-1d
    </desc>
    </descriptions>
    <key>
    us-east-1d
    </key>
    </describedValue>
    </enumeratedType>
    </field>
    <field>
    <name>
    minCount
    </name>
    <descriptions>
    <desc>
    Minimum Number of Instances
    </desc>
    <desc lang="fr_FR">
    Nombre minimal d'instances
    </desc>
    </descriptions>
    <help href="https://test154.rdu.rpath.com/catalog/clouds/ec2/help/launch/minInstances.html" />
    <type>
    int
    </type>
    <default>
    1
    </default>
    <constraints>
    <range>
    <min>
    1
    </min>
    <max>
    100
    </max>
    </range>
    </constraints>
    <required>
    true
    </required>
    </field>
    <field>
    <name>
    maxCount
    </name>
    <descriptions>
    <desc>
    Maximum Number of Instances
    </desc>
    <desc lang="fr_FR">
    Nombre maximal d'instances
    </desc>
    </descriptions>
    <help href="https://test154.rdu.rpath.com/catalog/clouds/ec2/help/launch/maxInstances.html" />
    <type>
    int
    </type>
    <default>
    1
    </default>
    <constraints>
    <range>
    <min>
    1
    </min>
    <max>
    100
    </max>
    </range>
    </constraints>
    <required>
    true
    </required>
    </field>
    <field>
    <name>
    keyName
    </name>
    <descriptions>
    <desc>
    SSH Key Pair
    </desc>
    <desc lang="fr_FR">
    Paire de clefs
    </desc>
    </descriptions>
    <help href="https://test154.rdu.rpath.com/catalog/clouds/ec2/help/launch/keyPair.html" />
    <enumeratedType>
    <describedValue>
    <descriptions>
    <desc>
    Og-QA
    </desc>
    </descriptions>
    <key>
    Og-QA
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    qauser
    </desc>
    </descriptions>
    <key>
    qauser
    </key>
    </describedValue>
    </enumeratedType>
    </field>
    <field>
    <name>
    securityGroups
    </name>
    <descriptions>
    <desc>
    Security Groups
    </desc>
    <desc lang="fr_FR">
    Groupes de s‚àö¬©curit‚àö¬©
    </desc>
    </descriptions>
    <help href="https://test154.rdu.rpath.com/catalog/clouds/ec2/help/launch/securityGroups.html" />
    <enumeratedType>
    <describedValue>
    <descriptions>
    <desc>
    Default EC2 Catalog Security Group
    </desc>
    </descriptions>
    <key>
    catalog-default
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    Generated Security Group
    </desc>
    </descriptions>
    <key>
    dynamic
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    Wide open
    </desc>
    </descriptions>
    <key>
    all to all
    </key>
    </describedValue>
    <describedValue>
    <descriptions>
    <desc>
    default group
    </desc>
    </descriptions>
    <key>
    default
    </key>
    </describedValue>
    </enumeratedType>
    <multiple>
    true
    </multiple>
    <default>
    catalog-default
    </default>
    <required>
    true
    </required>
    </field>
    <field>
    <name>
    remoteIp
    </name>
    <descriptions>
    <desc>
    Remote IP address allowed to connect (if security group is catalog-default)
    </desc>
    </descriptions>
    <type>
    str
    </type>
    <constraints>
    <length>
    128
    </length>
    </constraints>
    <hidden>
    true
    </hidden>
    </field>
    <field>
    <name>
    userData
    </name>
    <descriptions>
    <desc>
    User Data
    </desc>
    <desc lang="fr_FR">
    Data utilisateur
    </desc>
    </descriptions>
    <help href="https://test154.rdu.rpath.com/catalog/clouds/ec2/help/launch/userData.html" />
    <type>
    str
    </type>
    <constraints>
    <length>
    256
    </length>
    </constraints>
    </field>
    </dataFields>
    </descriptor>
